stages:
  - deploy

deploy_job:
  stage: deploy
  script:
    podman pull quay.io/rhn_engineering_mbultel/osm-fedora
    image_id=$(podman image list  | grep 'localhost/osm-fedora' | awk '{print $3}')
    podman run -t -v $PWD:/runner/env $image_id  ansible-playbook os_migrate.vmware_migration_kit.migration -i /runner/env/inventory.yml -e @vars.yml
