  - name: Add OpenShift and OpenStack entries to /etc/hosts
    become: true
    ansible.builtin.lineinfile:
      path: /etc/hosts
      line: "{{ item }}"
      create: yes
      state: present
    loop: "{{ host_entries }}"