---
- name: Migrate Guest from Vmware using nbdkit
  os_migrate.vmware_migration_kit.migrate:
    user:  "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    server: "{{ vcenter_hostname }}"
    vmname: "{{ vm_name }}"
    osmdatadir: "{{ os_migrate_data_dir }}"
    cbtsync: "{{ cbt_sync }} | default(false) | bool"
    convhostname: "{{ conv_host_name }} | default('') }}"
  register: migrate_output

- name: Set fact for disk ID
  set_fact:
    volume_uuid: "{{ nbdkit_output.ID }}"
