collections:
  - name: ansible.posix
  - name: openstack.cloud
    version: 2.2.0
  - name: os_migrate.os_migrate
    version: 1.0.1
  - name: community.vmware
    version: 4.5.0
  - name: community.general
  - name: os_migrate.vmware_migration_kit
    version: 1.3.4
